# -*- coding: utf-8 -*-
"""PROJEK BIG DATA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NmEb2wxYSNYCo9q3If9YFce174GVvwmh
"""

import time
from getpass import getpass
from io import StringIO

import numpy as np
import pandas as pd
import requests
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from IPython.display import clear_output, display

# --- Konfigurasi ---
MAP_KEY = getpass("Masukkan MAP_KEY FIRMS: ")   # tidak akan tampil di layar
SENSOR  = "VIIRS_SNPP_NRT"                      # NRT = data terbaru; pakai VIIRS_SNPP_SP untuk arsip lama
AREA    = "95,-11,141,6"                        # barat,selatan,timur,utara (Indonesia)
HARI_MUNDUR = 60                                # panjang data yang ditarik (hari)

# Parameter bagan kendali
BASELINE_DAYS = 30        # Fase I: hari awal untuk menghitung batas kendali
SIGMA_K       = 3         # lebar batas kendali (k-sigma)

# Parameter pola CEP
WINDOW_SIZE     = 7       # rolling window (hari)
Z_THRESH        = 2.0     # ambang z-score anomali titik
MIN_CONSECUTIVE = 3       # Threshold+Durasi: min. hari beruntun di luar batas
TREND_LEN       = 3       # Trend: min. hari konsisten naik/turun
SEQ_WINDOW      = 3       # Sequence: anomali FRP dalam N hari setelah anomali jumlah
ABSENCE_JAM     = 12      # Absence: batas jam tanpa deteksi baru

def tarik_firms(map_key, sensor, area, hari_mundur, chunk=5):
    """Menarik data hotspot per potongan 5 hari lalu menggabungkannya."""
    akhir = pd.Timestamp.utcnow().tz_localize(None).normalize()
    awal = akhir - pd.Timedelta(days=hari_mundur)
    potongan = []
    for tgl in pd.date_range(awal, akhir, freq=f"{chunk}D"):
        url = (f"https://firms.modaps.eosdis.nasa.gov/api/area/csv/"
               f"{map_key}/{sensor}/{area}/{chunk}/{tgl:%Y-%m-%d}")
        try:
            r = requests.get(url, timeout=60)
            r.raise_for_status()
            d = pd.read_csv(StringIO(r.text))
            if "latitude" in d.columns and len(d) > 0:
                potongan.append(d)
        except Exception as e:
            print(f"Gagal {tgl:%Y-%m-%d}: {e}")
        time.sleep(0.5)
    if not potongan:
        return pd.DataFrame()
    df = pd.concat(potongan, ignore_index=True).drop_duplicates()

    # Gabungkan tanggal + jam (UTC) jadi satu kolom waktu
    df["acq_time"] = df["acq_time"].astype(int).astype(str).str.zfill(4)
    df["waktu"] = pd.to_datetime(df["acq_date"] + " " + df["acq_time"],
                                 format="%Y-%m-%d %H%M", errors="coerce")

    # Saring confidence: VIIRS berupa huruf (l/n/h), MODIS berupa angka
    if df["confidence"].dtype == object:
        df = df[df["confidence"].isin(["n", "h", "nominal", "high"])]
    else:
        df = df[df["confidence"] >= 30]
    return df.dropna(subset=["waktu"]).reset_index(drop=True)


def agregasi_harian(df):
    """Mengubah titik hotspot menjadi deret harian: jumlah dan rata-rata FRP."""
    harian = (df.assign(tanggal=df["waktu"].dt.normalize())
                .groupby("tanggal")
                .agg(jumlah=("frp", "size"), frp_mean=("frp", "mean"))
                .asfreq("D"))
    harian["jumlah"] = harian["jumlah"].fillna(0)
    harian["frp_mean"] = harian["frp_mean"].interpolate(limit_direction="both")
    return harian.reset_index()

def consecutive_true_count(mask):
    """[F,T,T,T,F,T] -> [0,1,2,3,0,1]  (streak True yang berakhir di tiap baris)."""
    hasil, run = [], 0
    for v in mask.to_numpy():
        run = run + 1 if v else 0
        hasil.append(run)
    return pd.Series(hasil, index=mask.index)


def consecutive_same_sign(diff):
    """Panjang streak arah konsisten (naik/turun). Nilai 0 atau NaN memutus streak."""
    sign = np.sign(diff.fillna(0)).to_numpy()
    hasil, run, prev = [], 0, 0
    for s in sign:
        if s != 0 and s == prev:
            run += 1
        elif s != 0:
            run = 1
        else:
            run = 0
        hasil.append(run)
        prev = s
    return pd.Series(hasil, index=diff.index)


def batas_kendali_laney(c, baseline_n, k=3):
    """Bagan c' Laney: c-chart yang dikoreksi untuk overdispersi.
    Cocok untuk data hotspot yang ragamnya jauh lebih besar dari rata-ratanya."""
    base = c.iloc[:baseline_n]
    cbar = base.mean()
    z = (base - cbar) / np.sqrt(cbar)
    sigma_z = z.diff().abs().mean() / 1.128        # estimasi sigma dari moving range
    lebar = k * np.sqrt(cbar) * sigma_z
    return cbar, cbar + lebar, max(cbar - lebar, 0)


def analisis(harian):
    df = harian.copy()

    # --- Bagan kendali (Fase I dihitung dari baseline, Fase II memantau seluruh data) ---
    cl, ucl, lcl = batas_kendali_laney(df["jumlah"], BASELINE_DAYS, SIGMA_K)
    df["cl"], df["ucl"], df["lcl"] = cl, ucl, lcl

    # --- Anomali titik (z-score terhadap window sebelumnya) ---
    pm = df["jumlah"].shift(1).rolling(WINDOW_SIZE).mean()
    ps = df["jumlah"].shift(1).rolling(WINDOW_SIZE).std()
    df["z_jumlah"] = (df["jumlah"] - pm) / ps
    df["anomali_jumlah"] = df["z_jumlah"].abs() > Z_THRESH

    fm = df["frp_mean"].shift(1).rolling(WINDOW_SIZE).mean()
    fs = df["frp_mean"].shift(1).rolling(WINDOW_SIZE).std()
    df["z_frp"] = (df["frp_mean"] - fm) / fs
    df["anomali_frp"] = df["z_frp"].abs() > Z_THRESH

    # --- POLA 1: Threshold + Durasi ---
    df["streak_atas"]  = consecutive_true_count(df["jumlah"] > df["ucl"])
    df["streak_bawah"] = consecutive_true_count(df["jumlah"] < df["lcl"])
    df["pola_threshold"] = ((df["streak_atas"] >= MIN_CONSECUTIVE) |
                            (df["streak_bawah"] >= MIN_CONSECUTIVE))
    df["sisi"] = np.select([df["streak_atas"] >= MIN_CONSECUTIVE,
                            df["streak_bawah"] >= MIN_CONSECUTIVE],
                           ["atas (UCL)", "bawah (LCL)"], default="-")

    # --- POLA 2: Trend (rolling mean naik/turun konsisten) ---
    df["rolling_mean"] = df["jumlah"].rolling(WINDOW_SIZE).mean()
    selisih = df["rolling_mean"].diff()
    df["streak_trend"] = consecutive_same_sign(selisih)
    df["pola_trend"] = df["streak_trend"] >= TREND_LEN
    df["arah_trend"] = np.select([selisih > 0, selisih < 0], ["naik", "turun"], default="-")

    # --- POLA 3: Sequence + Correlation (anomali jumlah -> anomali FRP dalam window) ---
    anomali_jumlah_baru = (df["anomali_jumlah"].shift(1)
                           .rolling(SEQ_WINDOW, min_periods=1).max()
                           .fillna(0).astype(bool))
    df["pola_sequence"] = df["anomali_frp"].fillna(False) & anomali_jumlah_baru
    return df


def cek_absence(df_titik, batas_jam):
    """POLA 4: tidak ada deteksi hotspot baru melebihi batas jam."""
    terakhir = df_titik["waktu"].max()
    gap_jam = (pd.Timestamp.utcnow().tz_localize(None) - terakhir).total_seconds() / 3600
    return gap_jam > batas_jam, gap_jam, terakhir


def buat_log(df):
    kejadian = []
    for _, r in df.iterrows():
        if r["pola_threshold"]:
            n = int(max(r["streak_atas"], r["streak_bawah"]))
            kejadian.append((r["tanggal"], "Threshold+Durasi",
                             f"Jumlah hotspot di {r['sisi']} batas kendali {n} hari beruntun",
                             int(r["jumlah"])))
        if r["pola_trend"]:
            kejadian.append((r["tanggal"], "Trend",
                             f"Rolling mean {r['arah_trend']} konsisten {int(r['streak_trend'])} hari",
                             int(r["jumlah"])))
        if r["pola_sequence"]:
            kejadian.append((r["tanggal"], "Sequence+Correlation",
                             "Anomali FRP menyusul anomali jumlah hotspot (dalam window)",
                             int(r["jumlah"])))
    log = pd.DataFrame(kejadian, columns=["tanggal", "pola", "deskripsi", "jumlah_hotspot"])
    return log.sort_values("tanggal", ascending=False).reset_index(drop=True)

def tampilkan(df_titik, df):
    absen, gap_jam, terakhir = cek_absence(df_titik, ABSENCE_JAM)
    last = df.iloc[-1]

    print("=" * 60)
    print(f"Deteksi terakhir : {terakhir}  ({gap_jam:.1f} jam lalu)")
    print(f"Jumlah hotspot terakhir: {int(last['jumlah'])}  |  FRP rata-rata: {last['frp_mean']:.2f}")
    print(f"Batas kendali -> CL: {last['cl']:.1f}  UCL: {last['ucl']:.1f}  LCL: {last['lcl']:.1f}")
    print("-" * 60)
    print("Threshold+Durasi :", f"BREACH {last['sisi']}" if last["pola_threshold"] else "Normal")
    print("Trend            :", f"{last['arah_trend']} ({int(last['streak_trend'])}x)" if last["pola_trend"] else "Tidak ada trend kuat")
    print("Sequence+Corr    :", "Terdeteksi" if last["pola_sequence"] else "Tidak ada")
    print("Absence          :", f"DATA HILANG {gap_jam:.1f} jam" if absen else "Normal")
    print("=" * 60)

    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, row_heights=[0.7, 0.3],
                        vertical_spacing=0.07,
                        subplot_titles=("Bagan Kendali c' Laney: Jumlah Hotspot Harian",
                                        "Rata-rata FRP Harian"))
    x = df["tanggal"]
    fig.add_trace(go.Scatter(x=x, y=df["jumlah"], mode="lines+markers", name="Jumlah hotspot",
                             line=dict(color="#1f77b4")), row=1, col=1)
    fig.add_trace(go.Scatter(x=x, y=df["cl"], mode="lines", name="CL",
                             line=dict(color="green")), row=1, col=1)
    fig.add_trace(go.Scatter(x=x, y=df["ucl"], mode="lines", name="UCL",
                             line=dict(dash="dash", color="red")), row=1, col=1)
    fig.add_trace(go.Scatter(x=x, y=df["lcl"], mode="lines", name="LCL",
                             line=dict(dash="dash", color="red")), row=1, col=1)
    fig.add_trace(go.Scatter(x=x, y=df["rolling_mean"], mode="lines", name="Rolling mean",
                             line=dict(color="#ff7f0e", width=1.5)), row=1, col=1)

    def tandai(mask, nama, warna, simbol, ukuran, baris=1, kolom="jumlah"):
        d = df[mask]
        if not d.empty:
            fig.add_trace(go.Scatter(x=d["tanggal"], y=d[kolom], mode="markers", name=nama,
                                     marker=dict(color=warna, symbol=simbol, size=ukuran)),
                          row=baris, col=1)

    tandai(df["anomali_jumlah"], "Anomali titik (z-score)", "red", "x", 8)
    tandai(df["pola_threshold"], "Pola Threshold+Durasi", "darkred", "diamond", 13)
    tandai(df["pola_trend"], "Pola Trend", "#9467bd", "triangle-up", 8)
    tandai(df["pola_sequence"], "Pola Sequence+Correlation", "black", "star", 13)

    fig.add_trace(go.Bar(x=x, y=df["frp_mean"], name="FRP rata-rata",
                         marker=dict(color="#a3c4dc")), row=2, col=1)
    tandai(df["pola_sequence"], "FRP anomali (sequence)", "black", "star", 11, baris=2, kolom="frp_mean")

    fig.add_vrect(x0=x.iloc[0], x1=x.iloc[min(BASELINE_DAYS, len(x)) - 1],
                  fillcolor="lightgray", opacity=0.25, line_width=0,
                  annotation_text="Fase I (baseline)", row=1, col=1)
    fig.update_layout(template="plotly_white", height=650,
                      legend=dict(orientation="h", yanchor="bottom", y=1.06, xanchor="left", x=0))
    fig.update_yaxes(title_text="Jumlah hotspot", row=1, col=1)
    fig.update_yaxes(title_text="FRP (MW)", row=2, col=1)
    fig.show()

    log = buat_log(df)
    print("\nEvent Pattern Log (terbaru di atas):")
    display(log.head(20) if not log.empty else "Belum ada pola CEP yang terdeteksi.")

titik = tarik_firms(MAP_KEY, SENSOR, AREA, HARI_MUNDUR)

if titik.empty:
    print("[PERINGATAN] Tidak ada data hotspot yang berhasil ditarik.")
    print("Silakan periksa kembali apakah MAP_KEY FIRMS yang Anda masukkan sudah benar.")
else:
    print("Total titik hotspot (setelah filter confidence):", len(titik))
    harian = agregasi_harian(titik)
    hasil = analisis(harian)
    tampilkan(titik, hasil)

POLL_SECONDS = 600     # FIRMS diperbarui beberapa kali sehari, jadi tidak perlu terlalu sering
N_ULANG = 3            # batasi jumlah putaran supaya sel tidak berjalan selamanya

for i in range(N_ULANG):
    clear_output(wait=True)
    titik = tarik_firms(MAP_KEY, SENSOR, AREA, HARI_MUNDUR)
    hasil = analisis(agregasi_harian(titik))
    print(f"Update ke-{i+1} | {pd.Timestamp.utcnow():%Y-%m-%d %H:%M} UTC")
    tampilkan(titik, hasil)
    if i < N_ULANG - 1:
        time.sleep(POLL_SECONDS)
